#!/bin/sh
set -e

echo Building container...
docker build -t ip-allocator .

echo Setting local config...
etcdctl set /kubermesh.github.io/ip-allocator/config/ipv4-base-network 172.16.0.1/24
etcdctl set /kubermesh.github.io/ip-allocator/config/ipv6-base-network 2001:db8::/71

echo Running container...
rm -rf target
mkdir -p target/units target/opts
docker run \
  --rm \
  --net host \
  --volume `pwd`/target:/target \
  ip-allocator test1

echo '----Network unit----'
cat target/units/dummy0.network
echo '----Docker Opts file----'
cat target/opts/ip-allocator-docker-opts.env
echo '----Kubelet Opts file----'
cat target/opts/ip-allocator-kubelet-opts.env
